name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5', '8.8.2', '8.8.3' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Install dependencies
      run: |
        cabal update
    - name: Build
      run: |
        cabal configure
        cabal build
    - name: Run tests
      run: cabal test
